[[redirects]]
  from = "/api/confirm"
  to   = "/.netlify/functions/confirm"
  status = 200

[[redirects]]
  from = "/api/share"
  to   = "/.netlify/functions/share"
  status = 200

[[redirects]]
  from = "/api/view"
  to   = "/.netlify/functions/view"
  status = 200

[[redirects]]
  from = "/api/lock"
  to   = "/.netlify/functions/lock"
  status = 200
